!INTERFILE  :=
!imaging modality := PT
name of data file := scatter_template.s
originating system := Downsampled LAFOV
!version of keys := STIR6.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
number of radionuclides := 1
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 1
matrix axis label [3] := view
!matrix size [3] := 57
matrix axis label [2] := axial coordinate
!matrix size [2] := { 40}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 65
minimum ring difference per segment := { 0}
maximum ring difference per segment := { 0}
Scanner parameters:=
  Scanner type := Downsampled LAFOV
  Number of rings                          := 40
  Number of detectors per ring             := 114
  Inner ring diameter (cm)                 := 82
  Average depth of interaction (cm)        := 0.7
  Distance between rings (cm)              := 2.63291
  Default bin size (cm)                    := 1.28
  View offset (degrees)                    := 0
  Maximum number of non-arc-corrected bins := 65
  Default number of arc-corrected bins     := 65
  Energy resolution         := 0.098
  Reference energy (in keV) := 511
  Maximum number of (unmashed) TOF time bins := 214
  Size of unmashed TOF time bins (ps)        := 17.9039
  TOF timing resolution (ps)                 := 214
  Number of blocks per bucket in transaxial direction         := 1
  Number of blocks per bucket in axial direction              := 1
  Number of crystals per block in axial direction             := 10
  Number of crystals per block in transaxial direction        := 21
  Number of detector layers                                   := 1
  Number of crystals per singles unit in axial direction      := 10
  Number of crystals per singles unit in transaxial direction := 21
  Scanner geometry (BlocksOnCylindrical/Cylindrical/Generic)  := Cylindrical
End scanner parameters:=
number of energy windows:=1
energy window lower level[1]:=435
energy window upper level[1]:=585
number of time frames := 1
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
